# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Eslint code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  TEST: production
jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Package
        run: yarn install
      - name: Check your code
        run: lerna run pre-commit
  # notify_telegram:
  #   needs: [eslint]
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Extract branch name
  #       shell: bash
  #       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  #       id: extract_branch
  #     - name: send default message
  #       if: ${{ github.ref == 'refs/heads/main' }}
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         format: html
  #         message: |
  #           A new code has just built in github
  #           Type: <b>${{github.event_name}}</b>
  #           Title: <a href="https://github.com/${{github.repository}}"><b>Release main</b></a>
  #           By: ${{github.actor}}.
  #           Branch: ${{steps.extract_branch.outputs.branch}}
  #           Commit: ${{ github.event.head_commit.message }}
  #     - name: send default message
  #       if: ${{ github.ref != 'refs/heads/main' }}
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         format: html
  #         message: |
  #           A new code has just built in github
  #           Type: <b>${{github.event_name}}</b>
  #           Title PR: <a href="https://github.com/${{github.repository}}/pull/${{github.event.number}}"><b>${{ github.event.pull_request.title }}</b></a>
  #           By: ${{github.actor}}.
  #           Branch: ${{github.head_ref}}
